<a href="https://colab.research.google.com/github/Latiefabdul/Learning_Session/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to NumPy**

# Import NumPy

In [ ]:
import numpy as np

In [ ]:
#Declare Array
a = np.array([[1,2,3],[4,5,6]]) #Matriks
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10],[11,12]]]) #Tensor
print("Matriks:")
print(a)
print("\n")
print("Tensor:")
print(b)

Matriks:
[[1 2 3]
 [4 5 6]]


Tensor:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#Ini untuk mencari tahu bentuk dari sebuah array/matriks/tensor
c=np.shape(a)
d=np.shape(b)
print(c)
print(d)

(2, 3)
(3, 2, 2)


In [ ]:
a.shape

(2, 3)

In [ ]:
#Untuk mengambil elemen yang spesifik (r, c)
print(a[0,1])

2


In [ ]:
#Untuk Mengambil row (r, :)
print(a[0,:])

[1 2 3]


In [ ]:
#untuk mengambil kolom (:, c)
print(a[:,1])

[2 5]


In [ ]:
#Cara mengganti Value di 2-D Array
a[1,1] = 10
a[1,2] = 12
print(a)

[[ 1  2  3]
 [ 4 10 12]]


# NumPy Array

## *1.NumPy Array*

In [ ]:
#Function untuk mendefinisikan nilai dalam array
#Single Dimensional Array
print(np.array([1,2,3,4,5,6,7,8])) #Vector
print('\n')

#Two-Dimensional Array
print(np.array([[1,2],[3,4],[5,6],[7,8]])) #Matriks
print('\n')

#Three-Dimensional Array
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #Tensor
print(arr3d)
print("\n")
print(arr3d[1,1,0])
print("\n")
print(arr3d.shape)

[1 2 3 4 5 6 7 8]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


7


(3, 2, 2)


## *2.NumPy Arange*

In [ ]:
#Function untuk mendefinisikan nilai-nilai yang berjarak sama dalam interval yang ditentukan dalam array
print(np.arange(8)) #Hanya Stop
print('\n')
print(np.arange(1,8)) #Start dan Stop
print('\n')
print(np.arange(1,18,3)) #Start, Stop, Step

[0 1 2 3 4 5 6 7]


[1 2 3 4 5 6 7]


[ 1  4  7 10 13 16]


## *3.NumPy zeros*

In [ ]:
#Function untuk menampilkan array baru degan ukuran tertentu dan berisi 0
#Default dtype adalah float
print(np.zeros(5))
print('\n')
print(np.zeros((5,5),dtype=int))

## *4.NumPy ones*

In [ ]:
#Function untuk menampilkan array baru degan ukuran tertentu dan berisi 1
#Default dtype adalah float
print(np.ones(5))
print('\n')
print(np.ones((3,4), dtype=int))

[1. 1. 1. 1. 1.]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Manipulasi Array

## *1. Reshape*

---




In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print('Array:')
print(a)
print('\n')

#Kemudian array di Re-Shape menjadi bentuk ordo 3x4
#Cara 1
# b = np.reshape(a,(3,4))

#Cara 2
b= a.reshape(3,4)
# print('Array yang dimodify:')
print(b)

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## *2. Flatten*

In [ ]:
#Array kembali menjadi bentuk Single-Dimensional Array
c = np.array(b).flatten()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(d)
print('\n')

#Cara 1
#e = np.array(d).flatten()

#Cara 2
e = d.flatten()
print(e)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[1 2 3 4 5 6 7 8]


## *3.Transpose*

In [ ]:
TransMat = np.array(b).transpose()
# Transmat = b.transpose
print(TransMat)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]




---




**Axis / Axes**


Digunakan untuk array yang lebih dari 1 Dimensi. Dalam 2-D array.


Axis 0 adalah sepanjang vertikal ke bawah melintasi baris (row).
Axis 1 adalah sepanjang horizontal ke samping melintasi kolom (column)

## *4.Concatenate*

In [ ]:
Arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Arr2 = np.array([[20,21,22],[23,24,25],[26,27,28]])

#Ini Concatenate dalam Axis 0
print("Concatenate 2 Array dalam axis 0:") #Baris / Row
print(np.concatenate((Arr1,Arr2)))

#Ini Concatenate dalam Axis 1
print("\nConcatenate 2 Array dalam axis 1:") #Kolom / Column
print(np.concatenate((Arr1,Arr2), axis = 1))

In [ ]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(1,3)
print(x)
print(y)
print("\n")
z = np.concatenate((x,y[:,None]),axis=1)
print(z)

[[1 2 3]
 [4 5 6]]
[1 2]


[[1 2 3 1]
 [4 5 6 2]]


## *5.Stack*

In [ ]:
Arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Arr2 = np.array([[20,21,22],[23,24,25],[26,27,28]])

#Ini Stack dalam Axis -1
print("Stack 2 Array dalam axis -1:")
print(np.stack((Arr1,Arr2), axis = -1))

#Ini stack dalam Axis 0
print("\nStack 2 Array dalam axis 0:")
print(np.stack((Arr1,Arr2)))

#Ini stack dalam Axis 1
print("\nStack 2 Array dalam axis 1:")
print(np.stack((Arr1,Arr2), axis = 1))

Stack 2 Array dalam axis -1:
[[[ 1 20]
  [ 2 21]
  [ 3 22]]

 [[ 4 23]
  [ 5 24]
  [ 6 25]]

 [[ 7 26]
  [ 8 27]
  [ 9 28]]]

Stack 2 Array dalam axis 0:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]

Stack 2 Array dalam axis 1:
[[[ 1  2  3]
  [20 21 22]]

 [[ 4  5  6]
  [23 24 25]]

 [[ 7  8  9]
  [26 27 28]]]


## *6.Split*

In [ ]:
SplitArr = np.array([5,2,6,7,3,4,4,3,1])
#Membagi array menajdi 3 subarrays yang sama jumlah isinya:
SplitMat = np.split(SplitArr,3)
print(SplitMat)

#Membagi array di posisi yang di tunjuk sesuai dengan 1-D array:
SplitMat = np.split(SplitArr,[1,3,5])
print('\n')
print(SplitMat)

## *7.Resize*

In [ ]:
#Mengubah size array, kalau size lebih besar maka terdapat salinan
ResizeArr = np.array([[1,2,3],[4,5,6]])
ResizeMat = np.resize(ResizeArr,(3,5))
print(ResizeMat)

[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]]


## *8.Append*

In [ ]:
InitialAppend = np.array([[1,2,3],[4,5,6]])

#Menggabungkan Array tanpa Axis (1-D array)
Append1 = np.append(InitialAppend, [7,8,9]) 
print(Append1)

#Menggabungkan Array dalam Axis 0 (2-D Array)
print('\n')
Append2 = np.append(InitialAppend, [[7,8,9]], axis=0) 
print(Append2)

#Menggabungkan Array dalam Axis 1 (2-D Array)
print('\n')
Append3 = np.append(InitialAppend, [[7,8,9],[10,11,12]], axis=1) 
print(Append3)

[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## *9.Insert*

In [ ]:
InitialArr = np.array([[1,2],[3,4],[5,6]])
#Insert tanpa axis, maka array akan di flatten (1-D array)
Insert1 = np.insert(InitialArr,2,[11,12]) #Arr, Insert di indeks keberapa, yg mau di insert
print(Insert1)
# print('\n')

# print(InitialArr)

#Insert dalam axis = 0
print('\n')
Insert2 = np.insert(InitialArr,2,[11,12], axis = 0) 
print(Insert2)

#Insert dalam axis = 1
print('\n')
Insert3 = np.insert(InitialArr,2,[11,12,13], axis = 1) 
print(Insert3)

[ 1  2 11 12  3  4  5  6]


[[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]]


[[ 1  2 11]
 [ 3  4 12]
 [ 5  6 13]]


## *10.Delete*

In [ ]:
InitialDel = np.arange(1,9).reshape(2,4)
print(InitialDel)

#Delete tanpa axis, maka array akan di flatten (1-D array)
print('\n')
Delete1 = np.delete(InitialDel,2) 
print(Delete1)

#Delete dalam axis = 0, Row 2 Terhapus
print('\n')
Delete2 = np.delete(InitialDel,0, axis = 0) 
print(Delete2)

#Delete dalam axis = 1, Column 2 Terhapus
print('\n')
Delete3 = np.delete(InitialDel,1, axis = 1) 
print(Delete3)

[[1 2 3 4]
 [5 6 7 8]]


[1 2 4 5 6 7 8]


[[5 6 7 8]]


[[1 3 4]
 [5 7 8]]


## *11.Unique*

In [ ]:
InitialUnique = np.array([5,2,6,2,7,5,6,8,2,4,2,2])
print(InitialUnique)
print('\n')

#Value yang unik dari array:
UniqueFirst = np.unique(InitialUnique)
print('Value yang unik dari array:')
print(UniqueFirst)
print('\n')

#Value yang unik dari array dan indeksnya:
UniqueSecond = np.unique(InitialUnique, return_index=True)
print('Value yang unik dari array dan indeksnya:')
print(UniqueSecond)
print('\n')


#Ada berapa value unik dalam array:
UniqueSecond,indices = np.unique(InitialUnique, return_counts=True)
print('Ada berapa value unik dalam array:')
print(UniqueSecond)
print(indices)
print('\n')

#ct= np.split(InitialUnique,2)
ct= np.split(UniqueSecond,2)
print(ct)

## *12.Slice*

In [ ]:
InitialSlc = np.arange(10)
print(InitialSlc)
print('\n')

#Slicing satu elemen
s2 = InitialSlc[2]
print('Slicing satu elemen:')
print(s2)
print('\n')

#Slicing mulai dari indeks sekian.....
s3 = InitialSlc[3:]
print('Slicing mulai dari indeks sekian:')
print(s3)
print('\n')

#Slicing stop di indeks sekian.....
s31 = InitialSlc[:5]
print('Slicing stop di indeks sekian:')
print(s31)
print('\n')

#Slicing values diantara indeks- indeks
s4 = InitialSlc[3:8]
print('Slicing values diantara indeks- indeks:')
print(s4)
print('\n')

#Slicing values dengan step / interval sekian.....
s5 = InitialSlc[::2]
print('Slicing values dengan step / interval sekian:')
print(s5)
print('\n')

#Slicing dengan semua parameter
# s = InitialSlc[slice(2,7,2)]
s = InitialSlc[2:7:2]
print('Slicing dengan semua parameter:')
print(s)
print('\n')

NameError: ignored

In [ ]:
a = np.arange(25).reshape(5,5)
print(a)

print(a[1:4,0:3])


NameError: ignored

# Experiment dengan Array

Mari membuat array dibawah ini <br>
[[1. 1. 1. 1. 1.]<br>
[1. 0. 0. 0. 1.]<br>
[1. 0. 9. 0. 1.]<br>
[1. 0. 0. 0. 1.]<br>
[1. 1. 1. 1. 1.]]

In [ ]:
out = np.ones((5,5))
print(out)
in_ = np.zeros((3,3))
print(in_)
in_[1,1] = 9 
print(in_)

#out[r:c]
out[1:4,1:4] = in_
print(out)